"""update category name

Revision ID: 37c93868c051
Revises: 59af9e2eb76c
Create Date: 2026-06-17 15:15:04.194176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c93868c051'
down_revision: Union[str, Sequence[str], None] = '59af9e2eb76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('category_name_key'), 'category', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('category_name_key'), 'category', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
