"""add type for category

Revision ID: 3bffc0d49c7a
Revises: cba4bc69f926
Create Date: 2026-07-19 12:42:12.031849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bffc0d49c7a'
down_revision: Union[str, Sequence[str], None] = 'cba4bc69f926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('type', sa.Enum('INCOME', 'OUTCOME', name='categorytype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'type')
    # ### end Alembic commands ###
